AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GMP CheckMaster AI - API 명세서 기반 백엔드

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        CORS_ORIGIN: "*"
        DYNAMODB_TABLE: "gmp-checkmaster-checklist-records"
        SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
        AWS_REGION: us-east-1
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  # DynamoDB 테이블
  GMPTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: gmp-checkmaster
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  # 인증 핸들러 - API 명세서 기준
  AuthHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth-handler/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GMPTable
      Events:
        WorkerLogin:
          Type: Api
          Properties:
            Path: /auth/worker
            Method: post
        AdminLogin:
          Type: Api
          Properties:
            Path: /auth/admin
            Method: post
        GetUsers:
          Type: Api
          Properties:
            Path: /auth/users
            Method: get

  # 체크리스트 핸들러 - API 명세서 기준
  ChecklistHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: checklist-handler/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GMPTable
      Events:
        SubmitChecklist:
          Type: Api
          Properties:
            Path: /checklist
            Method: post
        GetUserChecklist:
          Type: Api
          Properties:
            Path: /checklist/{user_id}
            Method: get
        GetChecklistDetail:
          Type: Api
          Properties:
            Path: /checklist/detail/{record_id}
            Method: get

  # AI 분석 핸들러 - API 명세서 기준
  AIAnalysisHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ai-analysis-handler/
      Handler: index.handler
      MemorySize: 512
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GMPTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
      Events:
        AnalyzeWound:
          Type: Api
          Properties:
            Path: /ai/analyze-wound
            Method: post

  # QR 코드 핸들러 - API 명세서 기준
  QRHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: qr-handler/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GMPTable
      Events:
        VerifyQR:
          Type: Api
          Properties:
            Path: /qr/verify
            Method: post
        ExpireQR:
          Type: Api
          Properties:
            Path: /qr/expire
            Method: put

  # 출입 로그 핸들러 - API 명세서 기준
  AccessLogHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: access-log-handler/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GMPTable
      Events:
        CreateLog:
          Type: Api
          Properties:
            Path: /access-log
            Method: post
        GetLogs:
          Type: Api
          Properties:
            Path: /access-log
            Method: get

Outputs:
  ApiGatewayEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
